name: Test

on: [commit]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build app
      run: flutter run

    - name: Install Maestro
      run: curl -Ls "https://get.maestro.mobile.dev" | bash

    - name: Install Facebook IDB tool
      if: runner.os == 'macOS'
      run: |
        brew tap facebook/fb
        brew install facebook/fb/idb-companion

    - name: Run tests
      run: maestro test filename.yml
      env:
        FLUTTER_VERSION: stable # Use a specific version of Flutter, if needed
